### ISSUE TITLE
searchEngineJump-NextStage 的站点图标请进一步 https 化

### ISSUE THREAD

**Issue by ivysrono** [ted423/rules-GM-stylish-UC#3]
https://github.com/gloomy-ghost/UpgradeMixedContent
浏览器默认会载入任何来源的图片，但如果使用了上面这个扩展，就会禁止掉不支持https的图片，破图很难看且影响载入速度。

**Comment by ted423** [comment]
我这边以后是试图取消掉所有的站点图标，不过现在拖延癌发作中
